### ISSUE TITLE
Bridge dynamically mirrors any stellar asset

### ISSUE THREAD

**Issue by prayagd** [pendulum-chain/pendulum-prototype#54]
**Description**

Currently the bridge supports only two type of tokens(USDC and EUR) that can be mirrored. We should support all type of tokens bridging. 

## Main idea
* user: doesn't make a payment to the escrow account but creates a claimable balance instead (one that is claimable by the escrow account)
* then our bridge
  * monitors whether there are new claimable balances in Stellar claimable by the escrow account
  * if there is a such a claimable balance, then
    * check the asset of the claimable balance
    * if such a trustline for the escrow account does not exist yet (keep book in the bridge pallet), then add a trustline to the escrow account
    * once the trustline is set or if it already existed, then claim the balance
    * after that proceed like for an incoming payment (typical deposit flow)

Some reading about claimable balances:
* https://medium.com/aquarius-aqua/claimable-balances-on-the-stellar-network-47c5cdf8a1e
* javascript stellar sdk and how to create and submit transactions
  * https://www.npmjs.com/package/stellar-sdk
  * https://developers.stellar.org/docs/tutorials/send-and-receive-payments/#send-a-payment
* how to monitor claimable balances: https://developers.stellar.org/api/resources/claimablebalances/

**Comment by TorstenStueber** [comment]
@morgueye4 try to first implement this in JS. Start with: how to create a claimable balance, how to monitor new claimable balances, how to read and validate new claimable balances, hot to set up trustlines, how to claim claimable balances.

**Comment by gonzamontiel** [comment]
Closing since related pull request is merged.
